wader/fq

README.md
`fq` is packaged in Nixpkgs as of https://github.com/NixOS/nixpkgs/pull/151871, so these instructions will work within a few days (once the master channel advances.)
=> doc: Add Nix instructions to readme

README.md
`fq` is now moved to the Arch Linux [community] repository:
<https://archlinux.org/packages/community/x86_64/fq/>
Signed-off-by: Orhun Parmaksız <orhunparmaksiz@gmail.com>
=> doc: Update installation instructions for Arch Linux

README.md
A new package has been created in the AUR for building
and installing `fq` from the latest git source:
<https://aur.archlinux.org/packages/fq-git/>
Signed-off-by: Orhun Parmaksız <orhunparmaksiz@gmail.com>
=> doc: Update instructions to mention AUR (VCS) package

format/pcap/pcap.go
Documentation wrong? seems to happen in real pcap files
=> pcap: Don't fail if incl_len > spanlen

pkg/interp/buffer.go, pkg/interp/match.jq, pkg/interp/testdata/match.fqtest
Just confusing and breaks symbolic grep for decode values (as they are buffers).
To get buffer use tobytes functions intstead.
=> interp: Remove buffer smartness for regexp match functions

format/mp4/boxes.go, format/mp4/mp4.go
Track size/count instead of just sizes which should decrease memory usage
making count sanity check unnecessary.
Fixes issue with huge mp4 files (80gb+) with lots of samples.
=> mp4: Improved stsz handling

format/flac/flac_frame.go
Spec says sample size can be 4-32 but that is probably before correcting for waste bits
=> flac: Don't allow zero subframe sample size

format/id3/id3v2.go
Fixes issue with mp3 frame that happens to have a 2,3 or 4 at byte 3 being seen as id3v2 header
=> id3v2: Should assert not validate magic

pkg/interp/interp.jq, pkg/interp/testdata/inputs.fqtest
null input to open means stdin but it as also erroneously also used as object key
to store the error.
=> interp: Fix handling of group decode error from stdin

format/mp3/mp3.go
This might break mp3s with large id3v2 chunks embedded into the stream but
i think that is rare and probably means it is a dump of a mp3 radio stream etc.
An alternative approach is to also look for id3v2 etc between frames but then the mp3
root value probably should be an array of mix of things instead of a struct, or rename
header/footer to metadata?
Related to #103
=> mp3: Decrease max sync seek length between frames to 4k

format/matroska/matroska.go, format/media.go, format/mpeg/aac_frame.go
Fixes issue failing on unknown or future aac standards
Also add missing object type passing for matroska
=> aac_frame: Only try decode object types we know about

doc/TODO.md, doc/usage.md, internal/bitioextra/zeroreadatseeker.go, pkg/bitio/bitio.go, pkg/bitio/ioreader.go, pkg/bitio/ioreadseeker_test.go, pkg/bitio/multireader.go, pkg/decode/decode.go, pkg/decode/value.go, pkg/interp/binary.go, pkg/interp/binary.jq, pkg/interp/buffer.jq, pkg/interp/decode.go, pkg/interp/dump.go, pkg/interp/funcs.go, pkg/interp/interp.go, pkg/interp/interp.jq, pkg/interp/match.go, pkg/interp/match.jq, pkg/interp/testdata/buffer.fqtest, pkg/interp/testdata/value_array.fqtest, pkg/interp/testdata/value_boolean.fqtest, pkg/interp/testdata/value_json_array.fqtest, pkg/interp/testdata/value_json_object.fqtest, pkg/interp/testdata/value_null.fqtest, pkg/interp/testdata/value_number.fqtest, pkg/interp/testdata/value_object.fqtest, pkg/interp/testdata/value_string.fqtest
Rename buffer to binary. Still some work left what to call buffer/binary in decode code.
Document decode value and binary type
Fix proper unit padding for tobytes and add still undocumenated extra padding argument.
Add some additional binary tests
=> binary,decode,doc: Rename buffer to binary and add some documentation

README.md
Adds instructions to installing `fq` from scoop which I [added recently](https://github.com/ScoopInstaller/Main/pull/3295).
(ignore the warnings, this is a fresh install of Windows)
We had some difficulty with licenses as `fq` isn't officially marked as MIT (even though the LICENSE file text is MIT).
=> Adds Windows Scoop instructions for fq in README.

pkg/interp/interp.go, pkg/interp/testdata/incudepath.fqtest
Make it easier to find parse error in init.jq etc
=> interp: Use absolute path in errors

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.44.1)
=> Update github-golangci-lint from 1.44.0 to 1.44.1

format/mp3/testdata/test.fqtest, format/mpeg/testdata/mp3-frame-mono-crc.fqtest, pkg/interp/internal.jq, pkg/interp/query.jq, pkg/interp/repl.jq, pkg/interp/testdata/bitops.fqtest, pkg/interp/testdata/exitcode.fqtest, pkg/interp/testdata/incudepath.fqtest, pkg/interp/testdata/inputs.fqtest, pkg/interp/testdata/repl.fqtest, pkg/interp/testdata/var.fqtest
Rewrite non-sub-repl queries as "q" -> ".[] | q" and pass in inputs as array.
Before each input did an eval.
Also fixup error message a bit, skip line:column when they dont make sense.
=> repl: Speedup multi input to sub-repl

pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/funcs.go, pkg/interp/interp.go
Speeds up interp quite a bit.
Also good as i've start to use more includes to make code easier to follow
where thigns come from and also makes jq-lsp happier.
Also rename evalContext to evalInstace to make it less confused with context.
=> interp: Skip redundant includes

pkg/interp/internal.jq
null value from f did not call fin.
fin was not always called last
Now fin is onyl called once
Might be cause of some weird repl bugs.
=> interp: Make _finally handle null, call fin once and last

internal/colorjson/encoder.go, pkg/cli/test.exp, pkg/interp/eval.jq, pkg/interp/help.jq, pkg/interp/interp.go, pkg/interp/repl.jq
repl now rewrites query to do implicit display inside the sub eval.
This makes it possible to interrupt eval and output in a better and faster way.
Make JSON encoder fail early on errors.
Add more interrupt tests.
=> interp,repl: Improved eval and output interrupt

internal/script/script.go, pkg/interp/binary.go, pkg/interp/binary.jq, pkg/interp/testdata/binary_stdout.fqtest
Padding could end up double.
Remove to*range($pad) as it probably just confusing to be able
to pad an existing range, what to show in hexdump etc? zero bits
that do not actuall exist at that range?
Add tests and binary stdout support to tests
=> interp: Remove to*range pad argument and fix stdout padding issue

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.45.0)
=> Update github-golangci-lint from 1.44.2 to 1.45.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.45.2)
=> Update github-golangci-lint from 1.45.0 to 1.45.2

format/dns/dns.go, format/dns/dns_tcp.go, format/format.go, format/inet/flowsdecoder/flowsdecoder.go, format/inet/testdata/flow_missing_synack.fqtest, format/pcap/shared.go, format/pcap/testdata/http_gzip.fqtest, format/pcap/testdata/ipv6_http.fqtest, format/pcap/testdata/many_interfaces.fqtest, format/pcap/testdata/sll2_tcp.fqtest, format/rtmp/rtmp.go, format/rtmp/testdata/rtmp_sample.cap.fqtest
rtmp: check port based on tcp direction
dns,rtmp: refactor to use tcp and udp port match helpers
flow: add has start/end to tcp to know if stream has missing bytes
=> tcp,udp: Refactor and make port matching better

go.mod, go.sum
Rebase on upstream main
Fix issue using JQValue as object index
Fix issue destructuring JQValue array
=> gojq: Fix JQValue index and destructuring issue and rebase fq fork

format/icc/icc_profile.go
Also code was mixing bytes and bit units, how could this have worked?
=> icc_profile: Correctly clamp align padding on EOF

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.46.0)
=> Update github-golangci-lint from 1.45.2 to 1.46.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.46.1)
=> Update github-golangci-lint from 1.46.0 to 1.46.1

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.46.2)
=> Update github-golangci-lint from 1.46.1 to 1.46.2

go.mod, go.sum
Rebase on master
Cherry-pick https://github.com/chzyer/readline/pull/202
=> readline: Update fq fork

internal/gojqextra/totype.go, pkg/interp/encoding.go, pkg/interp/testdata/encoding/toml.fqtest, pkg/interp/testdata/encoding/yaml.fqtest
Use smallest int type for int64, uint6 and *big.Int
Fixes integer serialization for yaml and toml for small integers, othweise
they will end up as strings.
=> interp: Improve type normalization and use it for toyaml and totoml

pkg/interp/decode.go, pkg/interp/encoding.go, pkg/interp/interp.go
I used to tojson and would crash in binary values are there were
not optins deciding how to format the strinh. Now just treat as utf8 string.
=> dump: Skip JQValueEx if there are not options

format/avro/avro_ocf.go, format/bzip2/bzip2.go, format/cbor/cbor.go, format/flac/flac.go, format/flac/flac_frame.go, format/flac/flac_streaminfo.go, format/gif/gif.go, format/gzip/gzip.go, format/id3/id3v2.go, format/inet/ipv4_packet.go, format/jpeg/jpeg.go, format/mp4/boxes.go, format/mpeg/avc_nalu.go, format/mpeg/hevc_nalu.go, format/mpeg/mp3_frame.go, format/mpeg/mpeg_pes_packet.go, format/ogg/ogg_page.go, format/pcap/pcap.go, format/pcap/pcapng.go, format/png/png.go, format/rtmp/rtmp.go, pkg/decode/decode.go, pkg/decode/read.go
Decode API design is that Try* returns error non-Try panics.
Also rename Must* as they should panic and introduce some new Try* functions
that were missing.
=> decode: Cleanup Try<f>/<f> pairs

pkg/interp/interp.jq, pkg/interp/options.jq, pkg/interp/testdata/args.fqtest, pkg/interp/testdata/argvars.fqtest, pkg/interp/testdata/options.fqtest
There is still an alias for --decode-file
=> interp: Rename --decode-file to --argdecode to be more consistent

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.47.0)
=> Update github-golangci-lint from 1.46.2 to 1.47.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.47.1)
=> Update make-golangci-lint from 1.47.0 to 1.47.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.47.2)
=> Update make-golangci-lint from 1.47.1 to 1.47.2

pkg/decode/decode.go
Fix issue with modified decoder on panic causing other panics as the ranges gets messed up
=> decode: Range decode with new decoder to preserve bit reader

go.mod, go.sum, internal/gojqextra/types.go, pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/testdata/gojq.fqtest, pkg/interp/testdata/value_array.fqtest, pkg/interp/testdata/value_boolean.fqtest, pkg/interp/testdata/value_json_array.fqtest, pkg/interp/testdata/value_json_object.fqtest, pkg/interp/testdata/value_null.fqtest, pkg/interp/testdata/value_number.fqtest, pkg/interp/testdata/value_object.fqtest, pkg/interp/testdata/value_string.fqtest
Feels like what one would expect when doing to_entries on a decode value struct etc,
that is get the pairs in same order as decoder wants.
Quite sure this used to the case but was change to sorted key order when
to_entries was move from bein implemented in jq to be internal for performance
reasons. Now internal gojq to_entries has a special case for JQValue objects.
Also use new gojq.JQType* constants for type strings and switch binary type
to look more like strings. Can still use _exttype to get "binary".
=> gojq: Preserve keys order for to_entries when used with JQValue

internal/gojqextra/types.go, pkg/interp/testdata/gojq.fqtest
Otherwise nested array/object JQValue:s could end up being JSON marshalled
=> xml,csv,interp: Handle JQValue when string normalizing

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.47.3)
=> Update make-golangci-lint from 1.47.2 to 1.47.3

doc/usage.md, format/xml/html.go, format/xml/testdata/html.fqtest, format/xml/testdata/xml.fqtest, format/xml/xml.go
Was hard to use when you dont know what indexes things will have. They are sill optioal for toxml
=> xml,html: Always include attrs and children in array mode

pkg/scalar/scalar.go
Later mappers should be able to rely on sym being a value of a certain type.
In this crash case tar.go  had this:
d.FieldUTF8NullFixedLen("mtime", 12, scalar.SymUParseUint(8), scalar.DescriptionSymUUnixTime)
If mtime was empty string SymUParseUint was not even called so did not bail out running
all mappers.
=> decode,scalar: Map empty string also else sym might ends up nil

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0)
=> Update make-golangci-lint from 1.47.3 to 1.48.0

go.mod, go.sum, pkg/interp/repl.jq, pkg/interp/testdata/gojq.fqtest
Update repl completion for new scope/0 function, now reports name/arity and is more correct
Support for experimental `rawstring` literals, similar to go raw string literals
Sticter number literals, now 0b,0o and 0x fail it they have invalud symbols, ex: 0b123
=> gojq: Update fq fork, new scope function, rawstring, stricter integers

pkg/interp/options.jq, pkg/interp/testdata/args.fqtest, pkg/interp/testdata/unicode.fqtest
Currently only used to make dump output a bit nicer.
=> interp: Add --unicode-output/-U to force use of unicode

format/flac/flac.go, format/flac/flac_frame.go
As was mentioned in the TODO of format/flac/flac.go
Please review. Go is new to me, and I don't understand the syntaxis used here, simple copy-paste-trial-error approach.
I think the problem was that (as in [flac.tcl, samples were read unsigned, but](https://github.com/wader/flac.tcl/pull/2)) samples were read unsigned instead of signed, but I really don't understand what `d.FieldRawLen` does, so maybe it didn't read any samples at all?
=> Fix decoding of FLAC raw entropy partition

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.49.0)
=> Update github-golangci-lint from 1.48.0 to 1.49.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.49.0)
=> Update make-golangci-lint from 1.48.0 to 1.49.0

format/xml/testdata/test.svg.fqtest, format/xml/xml.go
fromXML*: Collect namespaces before resolving to not relay on attribute order.
toXML*: Sort attributes, prefer non-namescaped first.
=> xml: Even more namespace fixes

format/all/help.fqtest, format/bitcoin/bitcoin_blkdat.go, format/bitcoin/bitcoin_block.go, format/format.go
Makes bitcoin_blkdat fails fast as it is part of probe group.
Speeds up reading a big JSON file etc.
=> bitcoin_blkdat,bitcoin_block: Make sure there is a header if blkdat

pkg/decode/decode.go, pkg/decode/value.go
=> perfomance: increase performance by map usage

pkg/decode/decode.go, pkg/decode/value.go, pkg/interp/decode.go
Will make it faster for struct with logs of fields and seems to
not cuase any significant difference for small structs.
All this really needs a rewrite somehow, maybe refactor into interfaces somehow? getting messy.
=> interp,decode: For struct use map to lookup field

.github/workflows/ci.yml, Makefile
This patch will allow running `make test` directly on platforms that Go's race detector doesn't support, for example, ARM and RISC-V.
=> test: Skip go test with -race by default

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.50.0)
=> Update make-golangci-lint to 1.50.0 from 1.49.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.50.0)
=> Update github-golangci-lint to 1.50.0 from 1.49.0

go.mod, go.sum
Fixes performance https://github.com/gomarkdown/markdown/issues/265
Should make it possible to fuzz all formats again. Before fuzzer timed out at times.
=> markdown,fuzz: Update gomarkdown

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.50.1)
=> Update github-golangci-lint to 1.50.1 from 1.50.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.50.1)
=> Update make-golangci-lint to 1.50.1 from 1.50.0

go.mod, go.sum
From upstream:
improve performance of assignment operators and del function improve jq compatibility of walk function (fix #195)
=> gojq: Update rebased fq fork

internal/ctxstack/ctxstack.go, internal/ctxstack/ctxstacl_test.go
Make sure there is a top cancel function before calling it. Fixes panic caused when interrupting decode before interp context has been pushed.
Also cleanup confusing naming a bit.
Thanks @pldin601 for reporting
=> interp: Fix panic when trigger before any context has been pushed

doc/usage.md, format/asn1/testdata/test.pem.fqtest, format/cbor/testdata/appendix_a.fqtest, format/json/testdata/tofromjson.fqtest, pkg/interp/options.jq, pkg/interp/testdata/args.fqtest, pkg/interp/testdata/binary.fqtest, pkg/interp/testdata/options.fqtest, pkg/interp/testdata/tovalue.fqtest, pkg/interp/testdata/value_array.fqtest, pkg/interp/testdata/value_null.fqtest, pkg/interp/testdata/value_object.fqtest
I think this is more intuitive but might in some case cause very large JSON output but maybe that less common or expected. In does cases i think you either want to use some other bits_format (md5, truncate, etc) or you delete/transform the jq value before turn it into JSON.
Strings in gojq are binary safe so you can use to hold raw bytes. But note that convert the binary into JSON is lossy, same as the JSON standard.
Add bits_format option documentation.
=> interp: Change default bits_format=string

pkg/interp/binary.jq, pkg/interp/testdata/binary.fqtest
Instead use tobytes etc if binary matching is what is wanted
=> interp: Don't auto convert to binary for string functions, is just confusing

.goreleaser.yml
Also some cleanup
https://goreleaser.com/deprecations/#archivesreplacements
=> goreleaser: Use name_template instead of deprecated archive replacements

format/mp4/boxes.go, format/mp4/testdata/aac.fqtest, format/mp4/testdata/dash.fqtest
Is defined as int32 but is a string in practive it seems
=> mp4: sgpd,sbgp: Change grouping_type to a string

format/mp4/boxes.go, format/mp4/testdata/udta_no_length.fqtest
Try distinguish by probing length field. Should probably be improved, what does ffmpeg do?
Regression from c3e3b3e90dd42ab379fa00a74168ce8c41ad8ef5 #556
=> mp4: udta: Handle box with value rest of box

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.51.0)
=> Update github-golangci-lint to 1.51.0 from 1.50.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.51.0)
=> Update make-golangci-lint to 1.51.0 from 1.50.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.51.1)
=> Update make-golangci-lint to 1.51.1 from 1.51.0

format/toml/testdata/toml.fqtest, format/toml/toml.go, format/xml/xml.go
encoding/xml and github.com/BurntSushi/toml both reads a lot before detecting that it can't decode. Now we instead read one UTF-8 and make sure it's valid xml or toml 
Should speed up probing
Relatd to #586 bigzero-zip.zip
=> toml,xml: Fail fast on invalid content

pkg/cli/cli.go, pkg/interp/interp.go, pkg/interp/testdata/completion.fqtest
readline Config was used to pass completer function per readline call, was changed in #612 and caused regression. Now use our own member in stdOS to pass it instead.
Add a test but test script completer is implemented differently.
=> interp: Fix input completion regression in sub-REPLs

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.52.0)
=> Update make-golangci-lint to 1.52.0 from 1.51.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.52.1)
=> Update github-golangci-lint to 1.52.1 from 1.52.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.52.2)
=> Update github-golangci-lint to 1.52.2 from 1.52.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.52.2)
=> Update make-golangci-lint to 1.52.2 from 1.52.1

doc/usage.md, pkg/interp/help.jq, pkg/interp/interp.jq, pkg/interp/options.jq, pkg/interp/testdata/args.fqtest, pkg/interp/testdata/options.fqtest, pkg/interp/testdata/value_output.fqtest
Idea is to skip display so that JSON is outputted instead of showing tree and hexdump etc.
=> interp: Add --value-output/-V option to do tovalue before output

internal/gojqex/totype.go, pkg/interp/decode.go, pkg/interp/interp.jq, pkg/interp/testdata/tovalue.fqtest, pkg/interp/testdata/value_output.fqtest
Now ex "tovalue | .some.thing" on a decode value will make some.thing be jq value instead of a decode value which woud be displayed as a decode treee, seems confusing.
I think this is more intuetive and make more sense.
=> interp: Make tovalue output behave as jq value

pkg/interp/init.jq, pkg/interp/interp.jq, pkg/interp/testdata/binary_stdout.fqtest
So raw binay is only outputted if stdout is not a terminal and "... | d" is not used.. fq -n '[1,2,3] | tobytes' | cat > binary
fq -n '[1,2,3] | tobytes | d' | cat > hexdump
=> interp: Don't output raw binary if display is called explicitly

CHANGES.md, Makefile, README.md, doc/TODO.md, doc/dev.md, doc/formats.md, doc/mdsh.go, doc/presentations/bts2022/README.md, doc/presentations/bts2022/jq3, doc/usage.md, internal/ctxreadseeker/ctxreadseeker.go, pkg/cli/test_repl.exp, pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/decode.jq, pkg/interp/internal.jq, pkg/interp/match.go, pkg/interp/options.jq, pkg/interp/repl.jq
Found via `codespell -S format -L bu,ue,trys,nd,tbe,te,trun,actuall`
=> doc: fix typos

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.53.1)
=> Update make-golangci-lint to 1.53.1 from 1.52.2

README.md
Arch Linux recently merged all entries in its 'community' repository into 'extra' (https://archlinux.org/news/git-migration-announcement/). This commit updates the README to reflect this change.
=> doc: Fix broken link in README

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.53.2)
=> Update make-golangci-lint to 1.53.2 from 1.53.1

CHANGES.md, go.mod, go.sum, pkg/interp/testdata/value_array.fqtest, pkg/interp/testdata/value_boolean.fqtest, pkg/interp/testdata/value_json_array.fqtest, pkg/interp/testdata/value_json_object.fqtest, pkg/interp/testdata/value_null.fqtest, pkg/interp/testdata/value_number.fqtest, pkg/interp/testdata/value_object.fqtest, pkg/interp/testdata/value_string.fqtest
Changes from upstream:
8fcc90e implement abs function
cbbd4bb fix default module paths assuming gojq is located in a bin directory 45d4c5b change behavior of walk with multiple outputs 846cf99 fix stderr to output strings in raw format c352d50 change zero division to produce an error when dividend is zero d579009 fix empty string repeating with the maximum integer d4de65c fix string multiplication by zero to emit empty string 04b48fd remove deprecated leaf_paths function
c882861 bump up version to 0.12.13
c310d5d update CHANGELOG.md for v0.12.13
8fb5cc3 update dependencies
fb00b66 improve error message of indices, setpath, delpaths functions
=> gojq: Update fq fork

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.54.0)
=> Update make-golangci-lint to 1.54.0 from 1.53.3

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.54.2)
=> Update make-golangci-lint to 1.54.2 from 1.54.1

pkg/interp/decode.go, pkg/interp/testdata/completion.fqtest, pkg/interp/testdata/value.fqtest, pkg/interp/testdata/value_array.fqtest, pkg/interp/testdata/value_boolean.fqtest, pkg/interp/testdata/value_json_array.fqtest, pkg/interp/testdata/value_null.fqtest, pkg/interp/testdata/value_number.fqtest, pkg/interp/testdata/value_shadow.fqtest, pkg/interp/testdata/value_string.fqtest
For fromjson and other "value" decode values fq make then behave both like a normal jq value and decode value. This is to make tobytes, format etc work. Before all _* would be treated as special keys. Now they are first looked up in the wrapped value and then as decode values.
Also now ._key that don't exist reutrn null instead of throw error.
$ fq -n '`{"_format": 123}` | fromjson | ._format' Now:
123
Before:
"json"
$ fq -n '`{}` | fromjson | ._missing'
Now:
null
Before
error
=> decode,interp: Don't shadow _key and error on missing _key

pkg/interp/binary.jq, pkg/interp/testdata/binary.fqtest
The thing splitted on should not be included.
=> interp: split: Correctly split binary

go.mod, go.sum
Fixes https://nvd.nist.gov/vuln/detail/CVE-2023-42821
=> mod: Update golang.org/x/exp and github.com/gomarkdown/markdown

format/riff/avi.go
When > 0 split sample into sub samples
=> avi: Handle stream sample size

format/json/jq.jq, format/json/testdata/jq.fqtest
Thanks @emanuele6 for reporting
=> interp: Better from_jq error handling

doc/formats.md, format/format.go, format/riff/avi.go, format/riff/avi.md, format/riff/testdata/avc.avi.fqtest, format/riff/testdata/flac.avi.fqtest, format/riff/testdata/help_avi.fqtest, format/riff/testdata/mp3.avi.fqtest, format/riff/testdata/pcm.avi.fqtest
This is used for >1gb files. Disable decode will speed up deocde a lot but will probably also produce some gaps as same part of the movi chunks will not be reference by the indx index.
=> avi: Add extended chunks support and option

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.55.0)
=> Update make-golangci-lint to 1.55.0 from 1.54.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.55.1)
=> Update make-golangci-lint to 1.55.1 from 1.55.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2)
=> Update make-golangci-lint to 1.55.2 from 1.55.1

format/mp4/boxes.go, format/mp4/mp4.go, format/mp4/testdata/aac.fqtest, format/mp4/testdata/av1.fqtest, format/mp4/testdata/avc.fqtest, format/mp4/testdata/dash.fqtest, format/mp4/testdata/flac.fqtest, format/mp4/testdata/fragmented.fqtest, format/mp4/testdata/hevc.fqtest, format/mp4/testdata/in24.fqtest, format/mp4/testdata/lpcm.fqtest, format/mp4/testdata/mp3.fqtest, format/mp4/testdata/mpeg2.fqtest, format/mp4/testdata/opus.fqtest, format/mp4/testdata/png.mp4.fqtest, format/mp4/testdata/png_no_hdlr.mp4.fqtest, format/mp4/testdata/stz2.fqtest, format/mp4/testdata/vorbis.fqtest, format/mp4/testdata/vp9.fqtest, format/prores/testdata/prores_frame.fqtest
Also add field for data reference url
Fixes FileFormatConformance/data/file_features/published/isobmff/02_dref_edts_img.mp4
=> mp4: Don't decode samples if track has external data reference

go.mod, go.sum
[Source diff cca60bf24c9f..81f0f2329ad3](https://github.com/ergochat/readline/compare/vcca60bf24c9f..v81f0f2329ad3)
=> Update ergochat-readline to 81f0f2329ad3 from cca60bf24c9f

go.mod, go.sum
ircdog PR here: https://github.com/ergochat/ircdog/pull/47
Excited for this! Are you seeing anything unexpected in testing? Have you been testing on Windows? (I did some Windows testing but I should probably do some more before the release.)
=> bump readline to 0.1.0-rc1

.github/workflows/ci.yml, pkg/cli/cli.go, pkg/fqtest/fqtest.go, pkg/interp/interp.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.56.0)
=> Update github-golangci-lint to 1.56.0 from 1.55.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.56.0)
=> Update make-golangci-lint to 1.56.0 from 1.55.2

doc/usage.md, pkg/cli/cli.go
Got fed up with ~/Library/Application Support/fq
=> interp: Support ~/.config/fq as fallback on macOS

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.56.1)
=> Update github-golangci-lint to 1.56.1 from 1.56.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.56.1)
=> Update make-golangci-lint to 1.56.1 from 1.56.0

format/fit/fit.go
I also used your type->size idea for the expected sizes which simplified the switch statements alot.
=> fit: Skip array fields on pre read messages

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.56.2)
=> Update github-golangci-lint to 1.56.2 from 1.56.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.56.2)
=> Update make-golangci-lint to 1.56.2 from 1.56.1

pkg/cli/test_exp.sh
`which` is non-portable and not part of POSIX, but we can use `command -v` for the same effect.
Debian [0] and Gentoo [1] are both trying to drop which from their base system.
[0] https://lwn.net/Articles/874049/
[1] https://bugs.gentoo.org/646588
=> pkg/cli/test_exp.sh: use command -v

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.57.0)
=> Update make-golangci-lint to 1.57.0 from 1.56.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.57.1)
=> Update make-golangci-lint to 1.57.1 from 1.57.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.57.2)
=> Update make-golangci-lint to 1.57.2 from 1.57.1

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.58.0)
=> Update github-golangci-lint to 1.58.0 from 1.57.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.58.0)
=> Update make-golangci-lint to 1.58.0 from 1.57.2

go.mod, go.sum
[Release notes](https://github.com/ergochat/readline/releases/tag/v0.1.1)
=> Update gomod-ergochat-readline to 0.1.1 from 0.1.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.58.1)
=> Update github-golangci-lint to 1.58.1 from 1.58.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.58.1)
=> Update make-golangci-lint to 1.58.1 from 1.58.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.58.2)
=> Update make-golangci-lint to 1.58.2 from 1.58.1

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.59.0)
=> Update github-golangci-lint to 1.59.0 from 1.58.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.59.0)
=> Update make-golangci-lint to 1.59.0 from 1.58.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.59.1)
=> Update github-golangci-lint to 1.59.1 from 1.59.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.59.1)
=> Update make-golangci-lint to 1.59.1 from 1.59.0

go.mod, go.sum
[Release notes](https://github.com/ergochat/readline/releases/tag/v0.1.2)
=> Update gomod-ergochat-readline to 0.1.2 from 0.1.1

doc/usage.md, pkg/interp/interp.go, pkg/interp/testdata/binary.fqtest
Represent binary values into an array of bytes when turn values into JSON
=> interp: Add bits_format=byte_array support

doc/usage.md, pkg/interp/binary.go
Makes it possible to output all bytes or bits as integers in a binary value. Ex: [1,2,3] | [tobytes[]] -> [1,2,3]
=> intepr: Support each for binary values

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.60.2)
=> Update make-golangci-lint to 1.60.2 from 1.60.1

doc/formats.md, format/tap/tap.md, format/tzx/tzx.md
A small update to the TZX/TAP formats readme, with reference to the new `bits_format=byte_array`.
=> tzx: add readme instructions for bits_format=byte_array

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.60.3)
=> Update github-golangci-lint to 1.60.3 from 1.60.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.60.3)
=> Update make-golangci-lint to 1.60.3 from 1.60.2

go.mod, go.sum
[Release notes](https://github.com/ergochat/readline/releases/tag/v0.1.3)
=> Update gomod-ergochat-readline to 0.1.3 from 0.1.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.61.0)
=> Update make-golangci-lint to 1.61.0 from 1.60.3

format/matroska/ebml/gen/main.go, format/matroska/ebml_matroska/ebml_matroska.xml, format/matroska/ebml_matroska/ebml_matroska_gen.go, format/matroska/testdata/aac.fqtest, format/matroska/testdata/av1.fqtest, format/matroska/testdata/avc.fqtest, format/matroska/testdata/decode_samples.fqtest, format/matroska/testdata/flac.fqtest, format/matroska/testdata/hevc.fqtest, format/matroska/testdata/mp3.fqtest, format/matroska/testdata/mpeg2.fqtest, format/matroska/testdata/opus.fqtest, format/matroska/testdata/sweep-with-DC.mkvmerge13.mka.fqtest, format/matroska/testdata/unknown_size.fqtest, format/matroska/testdata/vorbis.fqtest, format/matroska/testdata/vp8.fqtest, format/matroska/testdata/vp9.fqtest
Update generator to support hex values
=> matroska: Update spec

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.62.0)
=> Update github-golangci-lint to 1.62.0 from 1.60.3

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.62.0)
=> Update make-golangci-lint to 1.62.0 from 1.61.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.62.2)
=> Update github-golangci-lint to 1.62.2 from 1.62.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.62.2)
=> Update make-golangci-lint to 1.62.2 from 1.62.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.0)
=> Update make-golangci-lint to 1.63.0 from 1.62.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.2)
=> Update github-golangci-lint to 1.63.2 from 1.63.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.2)
=> Update make-golangci-lint to 1.63.2 from 1.63.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.3)
=> Update make-golangci-lint to 1.63.3 from 1.63.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.4)
=> Update github-golangci-lint to 1.63.4 from 1.63.3

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.4)
=> Update make-golangci-lint to 1.63.4 from 1.63.3

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.2)
=> Update github-golangci-lint to 1.64.2 from 1.63.4

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.2)
=> Update make-golangci-lint to 1.64.2 from 1.63.4

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.4)
=> Update github-golangci-lint to 1.64.4 from 1.64.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.4)
=> Update make-golangci-lint to 1.64.4 from 1.64.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.5)
=> Update make-golangci-lint to 1.64.5 from 1.64.4

format/format.go, format/mp4/mp4.go, format/mp4/testdata/help_mp4.fqtest
Will skip create sample array for each track. Can be used to decode broken mp4s.
=> mp4: Add skip_samples options

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.6)
=> Update make-golangci-lint to 1.64.6 from 1.64.5

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.7)
=> Update github-golangci-lint to 1.64.7 from 1.64.6

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.7)
=> Update make-golangci-lint to 1.64.7 from 1.64.6

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.8)
=> Update github-golangci-lint to 1.64.8 from 1.64.7

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.8)
=> Update make-golangci-lint to 1.64.8 from 1.64.7

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.1.2)
=> Update github-golangci-lint to 2.1.2 from 2.1.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.1.2)
=> Update make-golangci-lint to 2.1.2 from 2.1.1

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.1.5)
=> Update github-golangci-lint to 2.1.5 from 2.1.2

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.1.5)
=> Update make-golangci-lint to 2.1.5 from 2.1.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.1.6)
=> Update github-golangci-lint to 2.1.6 from 2.1.5

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.1.6)
=> Update make-golangci-lint to 2.1.6 from 2.1.5

doc/usage.md
Fixed small typo in the examples of the "Encodings, serializations and hashes"section.
=> doc: fix small typo

doc/usage.md
`init.fq` does not automatically get loaded, `init.jq` however does
=> fix typo in doc

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.2.0)
=> Update github-golangci-lint to 2.2.0 from 2.1.6

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.2.0)
=> Update make-golangci-lint to 2.2.0 from 2.1.6

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.2.2)
=> Update github-golangci-lint to 2.2.2 from 2.2.1

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.3.0)
=> Update make-golangci-lint to 2.3.0 from 2.2.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.3.1)
=> Update github-golangci-lint to 2.3.1 from 2.3.0

Makefile
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v2.3.1)
=> Update make-golangci-lint to 2.3.1 from 2.3.0

doc/formats.md, format/flac/flac_frame.go, format/flac/testdata/frame.fqtest, format/flac/testdata/frame_sample_details.fqtest, format/flac/testdata/help_flac_frame.fqtest, format/flac/testdata/mono16.fqtest, format/flac/testdata/mono24.fqtest, format/flac/testdata/mono32.fqtest, format/flac/testdata/mono8.fqtest, format/flac/testdata/picture_seek_gain.fqtest, format/flac/testdata/stereo16.fqtest, format/flac/testdata/stereo24.fqtest, format/flac/testdata/stereo32.fqtest, format/flac/testdata/stereo8.fqtest, format/format.go, format/matroska/testdata/flac.fqtest, format/matroska/testdata/sweep-with-DC.mkvmerge13.mka.fqtest, format/mp4/testdata/flac.fqtest, format/ogg/testdata/flac.fqtest, format/riff/testdata/flac.avi.fqtest
=> flac: Add option to include sample and residuals details
