wader/fq

README.md
=> doc: add install instructions for Arch Linux

pkg/checksum/crc.go
Thanks Alexey Dokuchaev @danfe for report and fix.
Fixes #30
=> crc: Unbreak build on 32-bit arch

pkg/interp/decode.go, pkg/interp/interp.go
More related to decode than interp. Maybe should have a format.go?
=> interp: Move _registry to decode

format/matroska/matroska.go
Fixes issue with big webm/matroska files
Can be ignored with force decode
=> matroska: Assert sane tag size only for strings

doc/dev.md, doc/usage.md, internal/script/script.go, pkg/interp/interp.go
=> Unbreak @builtin include and tests on windows

pkg/interp/internal.jq, pkg/interp/testdata/debug.fqtest
Also add tests for print* and stderr
=> interp: Add stderr again for jq compat

doc/formats.svg, doc/formats_diagram.jq
Force all dep edges to go from east to north
=> doc: Improve formats graph a bit

format/bson/bson.go, format/bson/testdata/test.fqtest, format/cbor/cbor.go, format/msgpack/msgpack.go, format/msgpack/testdata/test.fqtest, internal/gojqextra/totype.go, pkg/decode/decode.go, pkg/interp/preview.go
Update msgpack, bson and cbor to use it.
=> decode,interp: Finish up nil value support

format/mp4/boxes.go, format/mp4/mp4.go
Also fatal error instead of silent ignore if index goes outside stsc or stco tables.
=> mp4: Refactor sample decode into something more sane

go.mod, go.sum
Should make it easier to package for debian etc
=> readline: Update to verison with less deps

.goreleaser.yml, Makefile, fq.go
=> fq: Embed version in source

.golangci.yml, dev/fuzzbytes.go, format/pcap/pcapng.go, pkg/decode/decode.go
Also add dev/fuzzbytes.go tool to convert fuzz input to raw bytes
=> pcapng,fuzz: Fix infinite loop by fatal error on block length <= 0

format/mp4/boxes.go, format/mp4/testdata/aac.fqtest, format/mp4/testdata/dash.fqtest
=> mp4,fuzz: Fatal error on infinite sgpd box entries

format/fuzz_test.go, pkg/decode/read.go
Fix string readers to not panic on make slice with bogus sizes
=> fuzz: Fuzz all formats

.github/workflows/ci.yml, .golangci.yml, internal/shquote/shquote.go, pkg/decode/decode.go, pkg/interp/interp.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.44.0)
=> Update github-golangci-lint from 1.43.0 to 1.44.0

fq.go, internal/script/script.go, pkg/cli/cli.go, pkg/fqtest/fqtest.go, pkg/interp/interp.go
Felt bad that main should have to know about it
=> interp: Add Platform() method to OS interface

.github/ISSUE_TEMPLATE/issue.md, Makefile, doc/dev.md, doc/display_decode_value.sh, doc/display_decode_value.svg, doc/display_decode_value_d.sh, doc/display_decode_value_d.svg, doc/display_decode_value_dv.sh, doc/display_decode_value_dv.svg, doc/display_json.sh, doc/display_json.svg, doc/usage.md
Also fixed some verbose -> dv leftovers
=> doc: Document display and some more jq hints

doc/formats.md, format/bencode/doc.md, format/bson/doc.md, format/cbor/doc.md, format/matroska/doc.md, format/mp4/doc.md, format/msgpack/doc.md, format/protobuf/doc.md, format/protobuf/protobuf.go
Fix and cleanup some other doc also
=> protobuf: Add note about sub message decoding

pkg/decode/decode.go, pkg/decode/value.go
Also move *Value.TryScalarFn to value.go
=> decode: Add scalars args to FieldRootBitBuf

LICENSE, README.md
=> doc: Add more license details

doc/TODO.md, doc/usage.md, internal/script/script.go, pkg/cli/cli.go, pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/funcs.jq, pkg/interp/interp.go, pkg/interp/repl.jq, pkg/interp/testdata/paste.fqtest
Also refactor readline and eval args into option struct and partinally start
addressing some side effects during completion.
=> interp: Add paste function to allow pasting text into REPL etc

pkg/interp/repl.jq, pkg/interp/testdata/completion.fqtest
=> repl: Fix completion of non-underscore extkeys

pkg/interp/interp.go, pkg/interp/testdata/completion.fqtest
Unbreaks completion using options
=> repl,interp: Make stdio work during completion

format/fuzz_test.go
Seems to run into timeouts (1s) if not as some formats can ends up allocating a lot
=> fuzz: Make it compile again and run one format per fuzz

go.mod, go.sum, pkg/interp/testdata/gojq.fqtest
Add bin,hex,oct bigint number literal tests
=> gojq: Rebase fq branch

format/mpeg/mpeg_spu.go
=> mpeg_spu: Fatal error on unknown cmd

go.mod
Also rearrange requires sections a bit
@xentripetal
=> bump: Add snappy config

format/matroska/testdata/path.fqtest, format/mp4/testdata/path.fqtest, internal/gojqextra/error.go, internal/gojqextra/types.go, pkg/interp/decode.go, pkg/interp/decode.jq, pkg/interp/interp.go, pkg/interp/testdata/inputs.fqtest, pkg/interp/testdata/value.fqtest
=> interp: Move _is_decode_value to jq

pkg/interp/internal.jq, pkg/interp/interp.jq, pkg/interp/options.jq
=> interp: Move opts eval to options.jq

go.mod, go.sum, pkg/interp/eval.jq, pkg/interp/help.jq, pkg/interp/query.jq, pkg/interp/repl.jq, pkg/interp/testdata/value.fqtest
tonumber now works with non-10 number literals
Also fix try precedences changes
=> gojq: Rebase fq fork and add support for non-10 base for tonumber

doc/formats.md, doc/formats.svg, format/macho/macho.md
Make macho format documentaion a bit more consistent.
=> doc: Regenerate and fix macho section size

pkg/cli/test.exp, pkg/interp/repl.jq
=> interp: Fix interrupt regression after query rewrite refactor

go.mod, go.sum
Includes from_entries optimization
=> gojq: Rebase fq fork

go.mod, go.sum
Include upstream speedups to:
flatten
join
ltrimstr
rtrimstr
startswith
endswith
min_by
max_by
min
max
sort
=> gojq: Rebase fq fork (speedup and fix range with JQValue)

go.mod, go.sum, pkg/interp/testdata/decode.fqtest
Add some decode value path and assign tests
=> gojq: Rebase fq fork. Fixes JQValue path tracking when iterating

go.mod, go.sum
[CHANGELOG](https://github.com/mitchellh/mapstructure/blob/master/CHANGELOG.md)
=> Update gomod-mapstructure from 1.4.3 to 1.5.0

README.md
https://ports.macports.org/port/fq/
=> readme: add MacPorts install details

go.mod, go.sum, internal/gojqextra/error.go, internal/gojqextra/types.go, pkg/interp/interp.go, pkg/interp/testdata/bitops.fqtest
Use new gojq.TypeOf and gojq.Preview
=> gojq: Update rebased fq fork

format/mp4/boxes.go, format/mp4/mp4.go, format/mp4/testdata/mvhd-tkhd-mdhd-mehd-v1.fqtest
Keep track of curren using box data stack instead of refrences in the context.
=> mp4,senc: Refactor current track/moof tracking and add senc box support

format/elf/elf.go
String table used for "needed" tags (the string seen with ldd etc) was using address as
offset which seem to work as it's usually the same as correct offset. But this is not true
for some ELFs. Then we have to look up offset by finding the section by address and then use
its offset for the string table. Hope this is the correct way.
Not sure how to produce a small test for this.
=> elf: Use correct offset to dynamic linking string table

go.mod, go.sum
Also some cleanup and fixup of commits
https://github.com/chzyer/readline/pull/207
=> readline: Rebase on top of tpodowd's redraw/completion fixes PR

internal/gojqextra/makefn_gen.go, internal/gojqextra/makefn_gen.go.tmpl, pkg/interp/interp.go, pkg/interp/registry.go
No need for env to be a function
=> gojqextra: Simplify function type helpers

go.mod, go.sum
[Source diff 1.1.0..1.2.0](https://github.com/BurntSushi/toml/compare/v1.1.0..v1.2.0)
=> Update gomod-BurntSushi/toml from 1.1.0 to 1.2.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.47.2)
=> Update github-golangci-lint from 1.47.1 to 1.47.2

doc/usage.md
Hopefully will get time to revamp how docs work
=> doc: Improve and cleanup text formats

.github/workflows/ci.yml, format/fuzz_test.go, pkg/interp/decode.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.47.3)
=> Update github-golangci-lint from 1.47.2 to 1.47.3

.github/workflows/ci.yml, dev/fuzzbytes.go, dev/tmpl.go, format/all/all.go, format/format.go, format/fuzz_test.go, format/id3/id3v2.go, format/inet.go, format/matroska/ebml_matroska/ebml_matroska_gen.go, format/media.go, format/mpeg/shared.go, format/rtmp/rtmp.go, internal/colorjson/encoder.go, internal/difftest/difftest.go, internal/gojqextra/types.go, internal/mathextra/float16.go, pkg/decode/decode.go, pkg/decode/read.go, pkg/fqtest/fqtest.go, pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/interp.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0)
=> Update github-golangci-lint from 1.47.3 to 1.48.0

format/matroska/ebml/gen/main.go, format/matroska/ebml_matroska/ebml_matroska_gen.go, format/matroska/testdata/aac.fqtest, format/matroska/testdata/av1.fqtest, format/matroska/testdata/avc.fqtest, format/matroska/testdata/flac.fqtest, format/matroska/testdata/hevc.fqtest, format/matroska/testdata/mp3.fqtest, format/matroska/testdata/mpeg2.fqtest, format/matroska/testdata/opus.fqtest, format/matroska/testdata/vorbis.fqtest, format/matroska/testdata/vp8.fqtest, format/matroska/testdata/vp9.fqtest
=> matroska: Strip newlines in description

format/csv/csv.go, format/format.go, format/json/json.go, format/json/testdata/json.fqtest, format/json/testdata/trailing.fqtest, format/toml/toml.go, format/xml/xml.go, format/yaml/testdata/trailing.fqtest, format/yaml/yaml.go
Turns out yaml is a superset of json
=> yaml: Error on trailing yaml/json

format/xml/testdata/test.svg, format/xml/testdata/test.svg.fqtest, format/xml/xml.go
Refactor element name handling a bit, return it instead, feels nicer.
=> xml: Keep track of default namespace and skip it element names

doc/formats.md, doc/usage.md, format/all/help.fqtest, format/format.go, format/xml/html.go, format/xml/testdata/html.fqtest, format/xml/testdata/test.svg.fqtest, format/xml/testdata/xml.fqtest, format/xml/xml.go, format/xml/xml.jq
=> xml: Switch from "-" to "@" as attribute prefix and make it an option

format/elf/elf.go
Makes it possible to decode shellcode snippets etc:
```
$ fq -n '"f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAeABAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAOAABAAAAAAAAAAEAAAAFAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAIAAAAAAAsDxmvwYADwU=" | frombase64 | elf | d'
|00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f|0123456789abcdef|.{}: (elf)
|                                               |                |  error: elf: BitBufRange: failed at position 0 (read size 4294967296 seek pos 0): outside buffer
|                                               |                |  header{}:
|                                               |                |    ident{}:
0x00|7f 45 4c 46                                    |.ELF            |      magic: raw bits (valid)
0x00|            02 …
```
=> elf: Treat missing string tables as empty to be more robust

go.mod, go.sum
Fixes: Iter function with no outputs in a path(...) throws errors https://github.com/itchyny/gojq/issues/191
=> gojq: Update fq fork

format/bitcoin/bitcoin_block.go, format/bplist/bplist.go, format/gzip/gzip.go, format/mp4/boxes.go, format/tar/tar.go, pkg/scalar/scalar.go, pkg/scalar/scalar_gen.go, pkg/scalar/scalar_gen.go.tmpl
Rework time helpers to use new functions
Fix panic in tar decoder where sym value might be missing
Still not very happy about the API but it's getting better.
=> decode,tar: Add scalar description and Try* helpers

go.mod, go.sum
[Source diff 0.3.7..0.3.8](https://github.com/golang/text/compare/v0.3.7..v0.3.8)
=> Update gomod-golang/text to 0.3.8 from 0.3.7

go.mod, go.sum
[Source diff 0.3.8..0.4.0](https://github.com/golang/text/compare/v0.3.8..v0.4.0)
=> Update gomod-golang/text to 0.4.0 from 0.3.8

go.mod, go.sum
[Source diff 1.2.0..1.2.1](https://github.com/BurntSushi/toml/compare/v1.2.0..v1.2.1)
=> Update gomod-BurntSushi/toml to 1.2.1 from 1.2.0

format/markdown/markdown.jq, format/riff/testdata/help_avi.fqtest, format/xml/testdata/help_xml.fqtest
Whitespace between words were not counted
=> interp,help: Properly count line length when breaking on whole words

format/flac/flac_metadatablocks.go, format/matroska/matroska.go, format/mp4/boxes.go, format/mpeg/mpeg_es.go, format/ogg/ogg.go
Will make it easier to refactor later on
=> decode: Make FieldFormat usage more consistent

format/apple/bplist/ns_keyed_archiver.jq
Let root arg be a lambda so torepr can be done once
=> bplist: Harmonize ns_keyed_archive jq style a bit

go.mod, go.sum
[Source diff 0.5.0..0.6.0](https://github.com/golang/text/compare/v0.5.0..v0.6.0)
=> Update gomod-golang/text to 0.6.0 from 0.5.0

go.mod, go.sum
Turrned out reading flag was no reset on del causing writes to be ignored
=> readline: Update fq fork to fix draw issue when using del key

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.51.1)
=> Update github-golangci-lint to 1.51.1 from 1.51.0

format/matroska/matroska.go
For non-master types assume size to be rest of file Still does not follow the ebml spec
=> matroska: Handle unknown size for non-master types a bit better

go.mod, go.sum
[Source diff 0.6.0..0.7.0](https://github.com/golang/text/compare/v0.6.0..v0.7.0)
=> Update gomod-golang/text to 0.7.0 from 0.6.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.51.2)
=> Update github-golangci-lint to 1.51.2 from 1.51.1

format/apple/bookmark/testdata/help_applebookmark.fqtest, format/apple/macho/testdata/help_macho.fqtest, format/asn1/testdata/help_asn1_ber.fqtest, format/avro/testdata/help_avro_ocf.fqtest, format/bencode/testdata/help_bencode.fqtest, format/bson/testdata/help_bson.fqtest, format/cbor/testdata/help_cbor.fqtest, format/csv/testdata/help_csv.fqtest, format/markdown/markdown.jq, format/markdown/testdata/help_markdown.fqtest, format/matroska/testdata/help_matroska.fqtest, format/mp4/testdata/help_mp4.fqtest, format/msgpack/testdata/help_msgpack.fqtest, format/protobuf/testdata/help_protobuf.fqtest, format/riff/testdata/help_avi.fqtest, format/rtmp/testdata/help_rtmp.fqtest, format/tzif/testdata/help_tzif.fqtest, format/wasm/testdata/help_wasm.fqtest, format/xml/testdata/help_html.fqtest, format/xml/testdata/help_xml.fqtest, format/zip/testdata/help_zip.fqtest, pkg/interp/help.jq
Also fix ugly last line break hack
=> help,markdown: Fix double line breaks when converting to text

go.mod, go.sum
[Source diff 0.7.0..0.8.0](https://github.com/golang/text/compare/v0.7.0..v0.8.0)
=> Update gomod-golang/text to 0.8.0 from 0.7.0

go.mod, go.sum
Some bug and redraw fixes from @tpodowd
Windows native ANSI support from @slingamn
=> readline: Update fq fork

pkg/cli/cli.go
I'm planning to remove `(*Instance).Config` as a public member in my fork [ergochat/readline](https://github.com/ergochat/readline), as part of a general project of shrinking the public API. This patch should be compatible with both chzyer/readline and the fork.
=> readline: remove direct access to (*Instance).Config

format/asn1/asn1_ber.go, format/bencode/bencode.go, format/bitcoin/bitcoin_block.go, format/bitcoin/bitcoin_script.go, format/bitcoin/bitcoin_transaction.go, format/bzip2/bzip2.go, format/cbor/cbor.go, format/dns/dns.go, format/gif/gif.go, format/id3/id3v1.go, format/id3/id3v2.go, format/jpeg/jpeg.go, format/matroska/matroska.go, format/mp4/boxes.go, format/mpeg/avc_pps.go, format/mpeg/mpeg_pes.go, format/mpeg/mpeg_pes_packet.go, format/mpeg/mpeg_spu.go, format/riff/aiff.go, format/rtmp/amf0.go, format/rtmp/rtmp.go, format/tls/tls.go, pkg/decode/decode.go, pkg/decode/decode_gen.go, pkg/decode/read.go, pkg/decode/types.json
Rename *d.Bits to UintBits as it return a uint
Add *d.Bits that return []byte
=> decode: Add float 80 reader

pkg/cli/cli.go
Should really add test for this
=> interp: Make completion work again

go.mod, go.sum
[Source diff 1.6.0..1.7.0](https://github.com/creasty/defaults/compare/v1.6.0..v1.7.0)
=> Update gomod-creasty-defaults to 1.7.0 from 1.6.0

format/format.go, internal/aheadreadseeker/aheadreadseeker.go, internal/ctxreadseeker/ctxreadseeker.go, internal/ioex/ioex.go, internal/progressreadseeker/progressreaderseeker.go, pkg/bitio/iobitreadseeker.go, pkg/bitio/iobitwriter.go, pkg/bitio/ioreader.go, pkg/bitio/ioreadseeker.go, pkg/bitio/limitreader.go, pkg/bitio/sectiontreader.go, pkg/decode/decode.go, pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/decode.jq
Will be used for probing via -d <string> and filename
=> interp,decode: Support decode group argument

format/apple/bookmark/testdata/help_applebookmark.fqtest, format/apple/macho/testdata/help_macho.fqtest, format/asn1/testdata/help_asn1_ber.fqtest, format/avro/testdata/help_avro_ocf.fqtest, format/bencode/testdata/help_bencode.fqtest, format/bson/testdata/help_bson.fqtest, format/cbor/testdata/help_cbor.fqtest, format/csv/testdata/help_csv.fqtest, format/markdown/markdown.jq, format/markdown/testdata/help_markdown.fqtest, format/matroska/testdata/help_matroska.fqtest, format/mp4/testdata/help_mp4.fqtest, format/msgpack/testdata/help_msgpack.fqtest, format/pcap/testdata/help_pcap.fqtest, format/protobuf/testdata/help_protobuf.fqtest, format/riff/testdata/help_avi.fqtest, format/rtmp/testdata/help_rtmp.fqtest, format/tls/testdata/help_tls.fqtest, format/tzif/testdata/help_tzif.fqtest, format/wasm/testdata/help_wasm.fqtest, format/xml/testdata/help_html.fqtest, format/xml/testdata/help_xml.fqtest, format/zip/testdata/help_zip.fqtest
Plan is to use it for man page etc and also some ansi renderer
=> help,markdown: Rewrote and made text rendering nicer

doc/demo.svg, doc/display_decode_value.svg, doc/display_decode_value_d.svg, doc/display_decode_value_dv.svg, doc/display_json.svg
Regenerate with new ansisvg that uses Courier with monospace as fallback
Related to #655
=> doc: Hopefully fix svg fixed font issue

doc/usage.md, format/json/json.go, internal/colorjson/encoder.go, internal/gojqex/totype.go, internal/gojqex/types.go, pkg/interp/binary.go, pkg/interp/decode.go, pkg/interp/dump.go, pkg/interp/interp.go, pkg/interp/testdata/binary.fqtest
```
$ cat random.bin.gz | fq -rV -o bits_format=hex .uncompressed
f6f2074cf77d449d
```
Also made unknown bit formats an error.
=> interp: Add hex bits format

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.53.1)
=> Update github-golangci-lint to 1.53.1 from 1.52.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.53.2)
=> Update github-golangci-lint to 1.53.2 from 1.53.1

go.mod, go.sum
[Source diff 0.9.0..0.10.0](https://github.com/golang/text/compare/v0.9.0..v0.10.0)
=> Update gomod-golang/text to 0.10.0 from 0.9.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.53.3)
=> Update github-golangci-lint to 1.53.3 from 1.53.2

go.mod, go.sum
[Source diff 0.10.0..0.11.0](https://github.com/golang/text/compare/v0.10.0..v0.11.0)
=> Update gomod-golang/text to 0.11.0 from 0.10.0

format/toml/testdata/toml.fqtest, go.mod, go.sum
[Source diff 1.2.1..1.3.2](https://github.com/BurntSushi/toml/compare/v1.2.1..v1.3.2)
=> Update gomod-BurntSushi/toml to 1.3.2 from 1.2.1

go.mod, go.sum
[Source diff 0.11.0..0.12.0](https://github.com/golang/text/compare/v0.11.0..v0.12.0)
=> Update gomod-golang/text to 0.12.0 from 0.11.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.54.1)
=> Update github-golangci-lint to 1.54.1 from 1.54.0

.github/workflows/ci.yml, format/inet/flowsdecoder/flowsdecoder.go, format/pcap/shared.go, format/riff/avi.go, format/xml/html.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.54.2)
=> Update github-golangci-lint to 1.54.2 from 1.54.1

go.mod, go.sum
[Source diff 0.12.0..0.13.0](https://github.com/golang/text/compare/v0.12.0..v0.13.0)
=> Update gomod-golang/text to 0.13.0 from 0.12.0

format/apple/bookmark/apple_bookmark.go, format/apple/bplist/bplist.go, format/bitcoin/bitcoin_block.go, format/gzip/gzip.go, format/matroska/ebml/ebml.go, format/matroska/matroska.go, format/matroska/testdata/sweep-with-DC.mkvmerge13.mka.fqtest, format/mp4/boxes.go, format/tls/tls.go, pkg/scalar/scalar.go
Also some refactor of shared date decode functions to allow unit
=> matroska: Decode ebml date type

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.55.0)
=> Update github-golangci-lint to 1.55.0 from 1.54.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.55.1)
=> Update github-golangci-lint to 1.55.1 from 1.55.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2)
=> Update github-golangci-lint to 1.55.2 from 1.55.1

go.mod, go.sum
[Source diff 0.13.0..0.14.0](https://github.com/golang/text/compare/v0.13.0..v0.14.0)
=> Update gomod-golang/text to 0.14.0 from 0.13.0

internal/mathex/float80.go
=> fq: Relicense float80 code to MIT

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.17.0 from 0.16.0

go.mod, go.sum
=> Update gomod-golang-x-term to 0.16.0 from 0.15.0

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.18.0 from 0.17.0

go.mod, go.sum
=> Update gomod-golang-x-net to 0.20.0 from 0.19.0

go.mod, go.sum
=> Update gomod-golang-x-term to 0.17.0 from 0.16.0

format/fit/fit.go
Some subfields are referencing fields that come after themselves in the message. This is allowed by spec, but means that data messages have to be pre-read to include all potential reference fields. I did this with d.PeekUintBits, but had to wrap in since that method ignores d.Endian.
Maybe my peekUintBitsEndian should be moved to the decode package?
=> fit: Fixed subfield referencing fields below self in message

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.20.0 from 0.19.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.57.0)
=> Update github-golangci-lint to 1.57.0 from 1.56.2

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.57.1)
=> Update github-golangci-lint to 1.57.1 from 1.57.0

.github/workflows/ci.yml
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.57.2)
=> Update github-golangci-lint to 1.57.2 from 1.57.1

go.mod, go.sum
=> Update gomod-golang-x-term to 0.19.0 from 0.18.0

go.mod, go.sum
=> Update gomod-golang-x-term to 0.20.0 from 0.19.0

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.23.0 from 0.22.0

go.mod, go.sum
[Source diff 1.3.2..1.4.0](https://github.com/BurntSushi/toml/compare/v1.3.2..v1.4.0)
=> Update gomod-BurntSushi/toml to 1.4.0 from 1.3.2

go.mod, go.sum
=> Update gomod-golang-x-term to 0.21.0 from 0.20.0

go.mod, go.sum
=> Update gomod-golang-x-term to 0.22.0 from 0.21.0

go.mod, go.sum
[Source diff 1.7.0..1.8.0](https://github.com/creasty/defaults/compare/v1.7.0..v1.8.0)
=> Update gomod-creasty-defaults to 1.8.0 from 1.7.0

.github/workflows/ci.yml, README.md, format/flac/flac.go, format/icc/icc_profile.go, format/json/json.go, format/leveldb/leveldb_log_blocks.go, format/matroska/matroska.go, format/mp3/mp3.go, format/mp4/boxes.go, go.mod, internal/hexdump/hexdump.go, internal/mathx/num.go, internal/stringsx/stringsx.go, pkg/cli/cli.go, pkg/decode/read.go, pkg/interp/dump.go, pkg/interp/interp.go, pkg/ranges/ranges.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.60.1)
=> Update github-golangci-lint to 1.60.1 from 1.59.1

doc/usage.md, pkg/interp/binary.go
Is a bad idea, behaves confusingly with .. etc. Maybe can be done in the future via some option to make all raw bits behave as arrays are instroduced.
=> intepr: Revert binary value each

.github/workflows/ci.yml, .golangci.yml, pkg/decode/decode.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.60.2)
=> Update github-golangci-lint to 1.60.2 from 1.60.1

pkg/interp/internal.jq, pkg/interp/testdata/debug.fqtest
Same as jq
Also some cleanup and simplifications
=> interp: Output raw strings for stderr/0

go.mod, go.sum
=> mod: Update github.com/gomarkdown/markdown

go.mod, go.sum
=> Update gomod-golang-x-net to 0.33.0 from 0.32.0

.github/workflows/ci.yml, format/matroska/matroska.go, format/mp4/boxes.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.63.0)
=> Update github-golangci-lint to 1.63.0 from 1.62.2

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.32.0 from 0.31.0

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.33.0 from 0.32.0

.github/workflows/ci.yml, format/xml/xml.go
[Release notes](https://github.com/golangci/golangci-lint/releases/tag/v1.64.5)
=> Update github-golangci-lint to 1.64.5 from 1.64.4

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.34.0 from 0.33.0

go.mod, go.sum
=> Update gomod-golang-x-net to 0.36.0 from 0.35.0

format/toml/testdata/toml.fqtest, go.mod, go.sum
[Source diff 1.4.0..1.5.0](https://github.com/BurntSushi/toml/compare/v1.4.0..v1.5.0)
=> Update gomod-BurntSushi/toml to 1.5.0 from 1.4.0

go.mod, go.sum
=> Update gomod-golang-x-net to 0.38.0 from 0.37.0

go.mod, go.sum
=> Update gomod-golang-x-crypto to 0.37.0 from 0.36.0

go.mod, go.sum
=> Update gomod-golang-x-net to 0.40.0 from 0.39.0

go.mod, go.sum
=> Update gomod-golang-x-net to 0.42.0 from 0.41.0
